apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xnlp.fullname" . }}-server
  labels:
    {{- include "xnlp.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.server.database.username | quote }}
  DB_PASSWORD: {{ .Values.server.database.password | quote }}
  OPENAI_API_KEY: {{ .Values.server.openai.apiKey | quote }}
  XNLP_SECURITY_API_KEYS: {{ .Values.server.security.apiKeys | quote }}
