apiVersion: v1
kind: Service
metadata:
  name: {{ include "xnlp.fullname" . }}-server
  labels:
    {{- include "xnlp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  selector:
    {{- include "xnlp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
